### PR TITLE
AAP-32490: Konflux build pipelines for Ansible Chatbot service

### PR DESCRIPTION
**Pull request by mabulgu**
## Description

Please see [AAP-32490](https://issues.redhat.com/browse/AAP-32490)

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [x] CI configuration change
- [x] Konflux configuration change

## Related Tickets & Documents

- Related Issue: [AAP-32490](https://issues.redhat.com/browse/AAP-32490)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
* Run the pipelines via Konflux UI

### CODE REVIEW

**Comment by jameswnl** [comment]
we need to go to the console dot ui to create Konflux application/component and start from there.

**Comment by mabulgu** [comment]
> we need to go to the console dot ui to create Konflux application/component and start from there.

On it thanks! I did not know we are able to test it before merging. Updating the dec part reg. that

**Comment by mabulgu** [comment]
@jameswnl converted this PR to draft as I found out I am able to test it before the merge.

**Comment by mabulgu** [comment]
@jameswnl @TamiTakamiya ready for your review. I think we can test the push pipeline once we merge this. It is more or less the same with the PR pipeline, just the image tagging changes so that should work as well.

Link to the successfully run PR pipeline: https://console.redhat.com/application-pipeline/workspaces/ansible-lightspeed/applications/ansible-chatbot-service/pipelineruns/ansible-chatbot-service-on-pr-4-l2f7p

**Review by jameswnl — APPROVED** [review]
The way I use Konflux is that, the PR will be created by Konflux when a Konflux component is created in the Konflux UI. Like [this one](https://github.com/ansible/ansible-chatbot-service/pull/8)

I am not sure if this way would work or not.  But anyway, I'll LGTM this.

**Comment by mabulgu** [comment]
> The way I use Konflux is that, the PR will be created by Konflux when a Konflux component is created in the Konflux UI. Like [this one](https://github.com/ansible/ansible-chatbot-service/pull/8)
> 
> 
> 
> I am not sure if this way would work or not.  But anyway, I'll LGTM this.

Hmm Konflux should not mandate where you start the conponent either via code or app but my bad that I did not understand what you say from scratch as I did lots of tekton stuff before and all via YAML.

Lets see how it goes and see if Konflux likes this or not (it is for sure that Tekton part is handled as we have a running pipeline but appwise I will see. In case of any problem I can save these two and create the components PRs and then replace them with my own YAML, but I hope we dont need these.

Thanks for your help so far!

**Pull request merged**
